# Generated by Django 5.2.1 on 2025-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status1',
            field=models.BooleanField(default=True),
        ),
    ]
