# Generated by Django 5.2.1 on 2025-05-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_remove_user_status_user_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status1',
            new_name='status',
        ),
    ]
