# Generated by Django 5.2.1 on 2025-05-30 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_pelerin_guide_pelerin_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelerin',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
    ]
