# Generated by Django 5.2.1 on 2025-05-30 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_alter_pelerin_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img1',
            field=models.ImageField(default='Hotel', upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img2',
            field=models.ImageField(default='Hotel', upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='img3',
            field=models.ImageField(default='Hotel', upload_to=''),
        ),
        migrations.AddField(
            model_name='pelerin',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelerin',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelerin',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
