# Generated by Django 5.2.1 on 2025-05-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_rename_status1_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={},
        ),
    ]
