# Generated by Django 5.2.1 on 2025-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0004_hotel_img1_hotel_img2_hotel_img3_pelerin_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelerin',
            name='type_pelerinage',
            field=models.CharField(choices=[('Hadjj', 'Hadjj'), ('Omra', 'Omra')], default='Omra', max_length=10),
        ),
    ]
