# Generated by Django 5.2.1 on 2025-05-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Session', '0004_alter_communication_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolue', models.BooleanField(default=False)),
                ('type_alerte', models.CharField(choices=[('perdu', 'Perdu'), ('urgence', 'Urgence Médicale'), ('chute', 'Chute')], max_length=10)),
                ('description', models.TextField()),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='Session.pelerin')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='Session.pelerin')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='Session.pelerin')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Session.hotel')),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Session.pelerin')),
            ],
        ),
    ]
