# Generated by Django 5.2.1 on 2025-05-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservation', '0001_initial'),
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='pelerin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='Session.pelerin'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='pelerin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='Session.pelerin'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='pelerin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='Session.pelerin'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Session.hotel'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pelerin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Session.pelerin'),
        ),
    ]
