# Generated by Django 5.2.1 on 2025-05-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_initial'),
        ('Session', '0002_pelerin_guide_pelerin_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rituel',
            name='duree',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RituelSteps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Session.pelerin')),
                ('rituel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.rituel')),
            ],
        ),
    ]
